name: "run Google Checks"

on:
  pull_request:
    branches: [ "main" ]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Build Android project"
        uses: vgaidarji/android-github-actions-build@v1.0.1
        with:
          args: "./gradlew assembleDebug"
      
      - name: Run Checks App Compliance analysis async
        uses: google-checks/checks-app-scan-github-action@v1.0.1
        with:
          account_id: ${{ secrets.CHECKS_ACCOUNT_ID }}
          app_id: ${{ secrets.CHECKS_APP_ID }}
          binary_path: "./app/build/intermediates/apk/debug/app-debug.apk"
          wait_for_report: true
        env:
          CHECKS_CREDENTIALS: ${{ secrets.CHECKS_CREDENTIALS }}

      - name: Clean build
        run: rm ./app/build/intermediates/apk/debug/app-debug.apk
